README.md
Source/Samples/ApplicationOutput.cs
Source/Samples/LICENSE
Source/Samples/MainWindow.cs
Source/Samples/Program.cs
Source/Samples/README.md
Source/Samples/Sections/Category.cs
Source/Samples/Sections/Dialogs/AboutDialogSection.cs
Source/Samples/Sections/ListSection.cs
Source/Samples/Sections/SectionAttribute.cs
Source/Samples/Sections/Widgets/ButtonSection.cs
Source/Samples/Sections/Widgets/EntrySection.cs

Just setting up samples as public domain.

Release samples to public domain

---

Source/Libs/GLibSharp/Timeout.cs
build.cake

Revert "Fix a null reference exception"

---

Source/Libs/PangoSharp/Context.cs

Revert "Fix getting Pango fonts"

---

Source/Libs/GLibSharp/VariantType.cs

Move public static fields below function pointers on which they depend

fix type initialization error in VariantType

---

Source/Samples/Sections/Widgets/DrawingAreaSection.cs

 [Samples] New DrawingArea sample

---

Source/Libs/GdkSharp/GdkSharp-api.xml

changed
SizeChanged, CompositedChanged, MonitorsChanged to signals in GdkSharp-api.xml
according to
https://developer.gnome.org/gdk3/stable/GdkScreen.html#GdkScreen-size-changed et al

Gdk.Screen: SizeChanged, CompositedChanged, MonitorsChanged as signals

---

Source/Libs/GtkSharp/CellRenderer.GetSize.cs
Source/Libs/GtkSharp/CellRenderer.cs
Source/Samples/Sections/Widgets/CellRendererSection.cs
Source/Samples/Sections/Widgets/CustomWidgets/CustomCellRenderer.cs

Gtk.CellRenderer.OnGetSize - Implementation
This is a managed implementation of
https://github.com/mono/gtk-sharp/blob/master/gtk/glue/cellrenderer.c
Added in Samples:
CustomCellRenderer.cs
adopted from
https://github.com/mono/gtk-sharp/commits/2.99.3/sample/CustomCellRenderer.cs

Gtk.CellRenderer: implement OnGetSize

---

Source/Libs/GtkSharp/FileChooserNative.cs
Source/Libs/GtkSharp/NativeDialog.cs

Fixed FileChooserNative

---

Source/Samples/Sections/Miscellaneous/PixbufSection.cs

adding an example for testing if pixbuf leaks
see discussion: https://github.com/GtkSharp/GtkSharp/issues/226 and https://github.com/GtkSharp/GtkSharp/issues/112

add test for https://github.com/GtkSharp/GtkSharp/issues/226

---

Source/Libs/GdkSharp/GdkSharp.metadata
Source/Libs/GtkSharp/GtkSharp.metadata

GDK: return list element types and owning.
GTK: out parameters.

Fixed some more APIs according to GTK docs

---

Source/Libs/GLibSharp/GException.cs

Read all GError fields in GException constructor and free GError memory.
Quote from [gtksharp2 fix](https://github.com/mono/gtk-sharp/pull/292): The original impl did not take into account exceptions marshalling across thread boundaries so it could end up with the error being accessed after being disposed.
Fixes #236.

GException improvements with multithreading

---

Source/Libs/Shared/Gapi.xsd

Added some elements that is supported in GapiCodegen to reduce number of validation errors in build log.

Extend XSD schema

---

Source/Libs/AtkSharp/AtkSharp.metadata
Source/Libs/GdkSharp/GdkSharp.metadata
Source/Libs/GtkSharp/GtkSharp-api.xml
Source/Libs/GtkSharp/GtkSharp.metadata
Source/Libs/GtkSourceSharp/GtkSourceSharp.metadata

Added element types, callback scopes.
Removed invalid rules (fewer "no matched nodes" messages in log).
Removed garbage property in GtkSharp-api.xml.

Fixed more metadata

---

Source/Libs/GtkSharp/CssProvider.cs
Source/Libs/GtkSharp/GtkSharp.metadata

Use embedded resources in CssProvider.LoadFromResource

---

Source/Libs/GdkSharp/PixbufAnimation.cs

Fix PixBufAnimation ctors leak

---

Source/Libs/CairoSharp/NativeMethods.cs
Source/Libs/CairoSharp/Surface.cs

Cairo API doc:
* [cairo-surface-get-device-scale](https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-get-device-scale)
* [cairo-surface-set-device-scale](https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-set-device-scale)

Add Cairo.Surface.DeviceScale property

---

Source/Libs/PangoSharp/Layout.cs
Source/Libs/PangoSharp/LayoutLine.cs
Source/Libs/PangoSharp/LogAttr.cs
Source/Libs/PangoSharp/PangoSharp.metadata

* Added `pango_layout_get_direction`
* Added `pango_layout_get_line_spacing` / `pango_layout_set_line_spacing` (fixes #258)
* Added `pango_layout_line_get_height`
* Added return type to `pango_itemize_with_base_dir`
* Fixed `pango_layout_line_get_x_ranges`
* Fixed `pango_layout_get_log_attrs` / `pango_layout_get_log_attrs_readonly` (using only readonly version because we make copy anyway, added LogAttr bitfield reading properties)

Added/fixed some Pango APIs

---

Source/Libs/GtkSharp/GtkSharp.metadata
Source/Tools/GapiCodegen/Property.cs

Added support for style properties and marked some style properties in GtkSharp.metadata.

Support style properties

---

Source/Samples/MainWindow.cs
Source/Samples/Sections/Widgets/TreeViewSection.cs

Features:
* Sort on header click.
* Add, edit, remove value in store (name column).
* Children items.
* Handlers for store events.

Added TreeView sample

---

Source/Libs/CairoSharp/Context.cs
Source/Libs/CairoSharp/Glyph.cs
Source/Libs/GLibSharp/HookList.cs
Source/Libs/GLibSharp/Marshaller.cs
Source/Libs/GLibSharp/Object.cs
Source/Libs/GLibSharp/Signal.cs
Source/Libs/GLibSharp/SignalClosure.cs
Source/Libs/GLibSharp/TimeVal.cs
Source/Libs/GdkSharp/Keymap.cs
Source/Libs/GtkSharp/ColorSelection.cs
Source/Libs/GtkSharp/ListStore.cs
Source/Libs/GtkSharp/StatusIcon.cs
Source/Libs/GtkSharp/Target.cs
Source/Libs/GtkSharp/TreeModelAdapter.cs
Source/Libs/GtkSharp/TreeModelFilter.cs
Source/Libs/GtkSharp/TreeModelSort.cs
Source/Libs/GtkSharp/TreeStore.cs
Source/Libs/GtkSharp/Widget.cs
Source/OldStuff/doc/en/GLib/Marshaller.xml
Source/Tools/GapiCodegen/ByRefGen.cs
Source/Tools/GapiCodegen/ClassBase.cs
Source/Tools/GapiCodegen/DefaultSignalHandler.cs
Source/Tools/GapiCodegen/GenerationInfo.cs
Source/Tools/GapiCodegen/ManualGen.cs
Source/Tools/GapiCodegen/Parameter.cs
Source/Tools/GapiCodegen/StructABIField.cs
Source/Tools/GapiCodegen/StructBase.cs
Source/Tools/GapiCodegen/StructField.cs
Source/Tools/GapiCodegen/SymbolTable.cs

See https://github.com/dotnet/corert/issues/5374#issuecomment-455706335
Current state in NativeAOT experiment is the same.

Make Marshal.SizeOf AOT friendly

---

Source/Libs/WebkitGtkSharp/WebkitGtkSharp-api.xml
Source/Libs/WebkitGtkSharp/WebkitGtkSharp-symbols.xml

add WebkitGtkSharp-symbols.xml to fix missing types

WebkitGtkSharp: fix missing types

---

Source/Libs/GtkSharp/Container.cs
Source/Libs/GtkSharp/GtkSharp-api.xml
Source/Samples/Sections/Miscellaneous/ContainerChildPropertiesSection.cs

* Fixed marshaling for reading child properties.
* Enabled child properties for Box, Grid, Stack in api xml.
* Added sample/test for using child properties (ChildPropertiesSection).

Fixed containers child properties

---

Source/Libs/GtkSharp/GtkSharp.metadata
Source/Libs/Shared/Gapi.xsd

Xsd for fewer generation warnings.

Marked more style properties and extended xsd schema

---

Source/Libs/GLibSharp/Marshaller.cs
Source/Samples/Sections/Dialogs/FileChooserDialogSection.cs

Fixes https://github.com/GtkSharp/GtkSharp/issues/345

[glib] Fix `g_filename_[from|to]_utf8` signatures for 64 bits platforms

---

Source/Libs/PangoSharp/PangoSharp.metadata

Fixed Pango+Cairo memory leak

---

Source/Libs/GtkSharp/GtkSharp.metadata
Source/Libs/GtkSharp/StyleContext.cs
Source/Samples/Sections/Miscellaneous/StyleContextSection.cs

Fixes #285 but not every property type is working ("padding" is crashing very often).
Added test section to samples.

Fixed StyleContext.GetProperty

---

Source/Libs/GtkSharp/CssNameAttribute.cs
Source/Libs/GtkSharp/GtkSharp.metadata
Source/Libs/GtkSharp/Widget.cs
Source/Samples/Sections/Miscellaneous/CssNameSection.cs

Added support for get/set css name of widget

---

Source/Libs/GdkSharp/GdkSharp.metadata

Fixed Gdk.Pixbuf.Flip memory leak

---

Source/Tools/GapiCodegen/Parameters.cs

if next == null, then next.Name is null access

Fixed null access in condition

---

Source/Libs/GLibSharp/IOChannel.cs
Source/Libs/GtkSharp/IconTheme.cs
Source/Libs/GtkSharp/Printer.cs

IOChannel: if func == null, then func_wrapper == null and access to func_wrapper.NativeDelegate
IconTheme: if value == null, then access to value.Length
Printer: if func == null, then func_wrapper == null and access to func_wrapper.NativeDelegate

Null access fixes

---

Source/Libs/CairoSharp/Context.cs

According to obsoletion comments calls was wrong

Fixed calls in obsolete methods

---

Source/Libs/GdkSharp/EventSelection.cs

Fixed null reference
