- Source/Samples/Samples.csproj
This hides embedded resources from IDEs so that there are no duplicate files.
> [Samples] Hide embedded resources

- Source/Libs/CairoSharp/Context.cs
- Source/Libs/GtkSharp/GtkSharp.metadata
While playing around with this library I noticed that there is no way of accesing clip areas for both Gtk and Cairo (apart from Allocation in Gtk).
> Fixed clip area related methods (Gtk and Cairo)

- Source/Libs/PangoSharp/PangoSharp.metadata
native name is PangoCoreTextFamily in Osx
> [FIX] PangoSharp metadata (osx)

- Source/Libs/GLibSharp/Object.cs
The garbage collector is not able to free the object if any signals are still present.
This will clean all the internal signals. Manually created signals should be unhooked by the developer.
> Free all internal signals, else the garbage collector is not able to free the object.

- Source/Libs/AtkSharp/AtkSharp-api.xml
- Source/Libs/GLibSharp/GLibSharp-api.xml
- Source/Libs/GdkSharp/GdkSharp-api.xml
- Source/Libs/GioSharp/GioSharp-api.xml
- Source/Libs/GtkSharp/Application.cs
- Source/Libs/GtkSharp/GtkSharp-api.xml
- Source/Libs/PangoSharp/PangoSharp-api.xml
- Source/Libs/PangoSharp/PangoSharp.metadata
- Source/Libs/Shared/GLibrary.cs
- Source/Tools/GapiCodegen/Ctor.cs
- Source/Tools/GapiCodegen/EnumGen.cs
- Source/Tools/GapiCodegen/Method.cs
- Source/Tools/GapiCodegen/OpaqueGen.cs
Stuff done:
- No longer allows a function that loads string, instead uses an enum, skips a find
- Added secondary library names for Windows Gtk 3 library
- Improved code for trying to load Gtk library to try all the filenames and print out the tried filenames in the DllNotFoundException
> Improve library loading code

- Source/Libs/GtkSharp/ComboBox.cs
- Source/Libs/GtkSharp/ComboBoxText.cs
If a Gtk.ComboBox is created without an Entry, referencing  ComboBox.Entry will generate an InvalidCastType exception since Child in this case is a CellRenderer rather than an Entry.
I've changed it to use 'as' so it will return null if there is no Entry.
I don't think it's worth checking HasEntry property?
Same issue occurs in Gtk.ComboBoxText.Entry.
In this case, ComboBoxText.Entry is actually hiding ComboBox.Entry, so since they are currently identical, I've just removed ComboBoxText.Entry so it inherits it from ComboBox instead.
> Combobox.entry fix invalid cast exception

- Source/Libs/GtkSharp/GtkSharp.metadata
GtkWidget.ListActionPrefixes() is currently returning a string, but it's mangled because the underlying gtk_widget_list_action_prefixes is actually returning a null-terminated array of strings...
[const gchar ** gtk_widget_list_action_prefixes (GtkWidget *widget);](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-list-action-prefixes)
So added a line to metadata file including null_term_array = 1
> Change GtkWidget.ListActionPrefixes() to return string[] 

- Source/Libs/GtkSharp/GtkSharp-api.xml
Gtk.SelectionData.Uris is currently returning a string, but the underlying gtk_selection_data_get_uris call is actually returning a null-terminated array of strings...
`gchar ** gtk_selection_data_get_uris (const GtkSelectionData *selection_data);`
Similarly for Gtk.SelectionData.SetUris()...
`gboolean gtk_selection_data_set_uris (GtkSelectionData *selection_data, gchar **uris);`
So added 2 x `null_term_array = "1"` to metadata file.
See #105
> Change Gtk.SelectionData Uris & SetUris to use string[]

- Source/Libs/GtkSharp/GtkSharp-api.xml
- Source/Libs/GtkSharp/GtkSharp.metadata
Update GtkSharp.metadata so following functions accept/return string[] instead of string:
GtkApplication.GetAccelsForAction
GtkApplication.SetAccelsForAction
GtkApplication.GetActionsForAccel
Should fix:
#142 Probably invalid signature for Gtk.Application.SetAccelsForAction
> Change Gtk.Application action/accel related calls to use string[]

- Source/Tools/GapiCodegen/OpaqueGen.cs
Adding code to remove the timeouthandler from source_handlers in Source.cs
The FinalizerInfo class generated by OpaqueGen.cs doesnt remove the TimeoutHandler Ids added to the static dictionary private static IDictionary<uint, SourceProxy> source_handlers in Source.cs .
This would lead to the memory growing continuously with each source_handler added. Could see it filling up GBs in matter of few hours when used with Gstreamer pipelines and objects created with Gstreamer-Sharp bindings for C#
> Fix for memory leak(Issue 135)

- Source/Libs/GtkSharp/Container.Forall.cs
- Source/Libs/GtkSharp/Container.cs
- Source/Samples/Sections/Widgets/CustomWidgets/PolarFixed.cs
- Source/Samples/Sections/Widgets/PolarFixedSection.cs
in Gtk.Container, implementation of ForAll(bool include_internals, Callback callback) is missing.
It's needed to subclass Custom Containers
this is a managed implementation.
in mono/gtksharp, its implemented with https://github.com/mono/gtk-sharp/blob/master/gtk/glue/container.c
For Testing, in Samples, a PolarFixed-Section with an adopted PolarFixed from 
https://github.com/mono/gtk-sharp/blob/master/sample/PolarFixed.cs
was added.
> Gtk.Container: implement missing ForAll(bool include_internals, Callback callback)

- Source/Libs/GLibSharp/Value.cs
If a GLib.Value happens to contain a `NULL` GLib.Variant and at some point is "unwrapped" to a managed `object` (e.g. in a [SignalClosure](https://github.com/GtkSharp/GtkSharp/blob/40773f3c881045e263abed1e13e05467c025a6fa/Source/Libs/GLibSharp/SignalClosure.cs#L164)), native GLib complains:
```
GLib-CRITICAL **: 21:17:12.546: g_variant_ref_sink: assertion 'value != NULL' failed
```
This happens because the GLib.Value -> GLib.Variant cast operator calls the `GLib.Variant (IntPtr)` constructor even if the pointer is a NULL pointer.
The warning is particularly annoying since this happens whenever a parameterless GLib.SimpleAction gets activated 😉
> Handle NULL in GLib.Value -> GLib.Variant cast operator

- Source/Libs/GtkSharp/Container.Forall.cs
A SIGSEGV occurs without this change  (Invalid pointer: 0x00 fix)
> Fix Container.ForAll

- Source/Libs/GtkSharp/CellRenderer.GetSize.cs
- Source/Libs/GtkSharp/Container.Forall.cs
Gtk.Container.gtksharp_container_base_forall & CellRenderer.gtksharp.cellrenderer_base_get_size: check if obj is null
if Widget.Dispose is called, TryGetObject can fail (=gives back null)
therefore check for null
> Gtk.Container & Gtk.CellRenderer: nullcheck in glue-methods

- Source/Libs/CairoSharp/Context.cs
This exposes the cairo_path_extents() method (https://www.cairographics.org/manual/cairo-Paths.html#cairo-path-extents), and is closely related to the existing StrokeExtents() method.
> Implement Cairo.Context.PathExtents()

- Source/Libs/GdkSharp/GdkSharp-api.xml
- Source/Libs/GdkSharp/GdkSharp.metadata
This exposes `gdk_pixbuf_get_from_window` and `gdk_pixbuf_get_from_surface` (https://developer.gnome.org/gdk3/stable/gdk3-Pixbufs.html#gdk-pixbuf-get-from-window) via Gdk.Pixbuf constructors. Previously they were in a hidden `GdkPixbuf_` class and unavailable.
Fixes: #174
> Add Gdk.Pixbuf constructors for a source Gdk.Window or Cairo.Surface.

- Source/Libs/GdkSharp/GdkSharp-api.xml
This was an issue with the changes in #176 - apologies for not testing this thoroughly enough!
`gdk_pixbuf_get_from_surface()` is in `libgdk`, not `libgdk_pixbuf` - this needs to be explicitly specified since 3a67da38 relocated these methods into `Gdk.Pixbuf`, which is underneath an element that specified `library="Library.GdkPixbuf"`
This fixes errors at run time when calling this method (similar for `gdk_pixbuf_get_from_window()`)
> Fix runtime errors when calling the Gdk.Pixbuf constructors that take Gdk.Window or Cairo.Surface

- Source/Libs/PangoSharp/PangoSharp.metadata
I tested this on OSX by adding the following code to `DrawingAreaSection::draw_text` in the samples:
```
var family = layout.Context.Families[0];
var faces = family.Faces;
```
This is similar to the fix for FontFamily in #35, and adds metadata for the parent class.
Without this, I found that the conversion to GObject failed in GLib.Object.GetObject and the pointer was deleted, corrupting memory for the next call.
Fixes: #159
> Fix crash when accessing Pango.FontFamily.Faces

- Source/Libs/GtkSharp/Container.cs
Properly marshal `gtk_container_class_find_child_property` with return type of pointer instead of struct. Then marshal pointer to struct manually.
Fixes #193.
> Fixed Container.ChildGetProperty

- Source/Libs/GdkSharp/PixbufLoader.cs
The `PixbufLoader.PixbufHandle` property is only used when creating new Pixbuf objects, which when you assign the handle to Raw it adds a reference already.  So we shouldn't add a reference when accessing the property.
Fixes #186
Fixes https://github.com/picoe/Eto/issues/1771
> Don't add reference to PixbufHandle

- Source/Libs/GtkSharp/NativeDialog.cs
Fixes crash with getting/setting `NativeDialog.Title` property with manual marshal UTF-8 string. Crash can be reproduced with some non-ascii (multibyte) chars in string.
> Manually marshal UTF-8 dialog title

- Source/Libs/GtkSharp/GtkSharp.metadata
changes
```c#
IScrollable.bool GetBorder(Gtk.Border border);
```
to
```c#
IScrollable.bool GetBorder(out Gtk.Border border);
```
as of 
https://github.com/GNOME/gtk/blob/b534752d5c0fc69a94fe9fe51abe1c047afa57c5/gtk/gtkscrollable.c#L292-L308
should be an **out** parameter
fix of https://github.com/GtkSharp/GtkSharp/issues/200
> IScrollable: GetBorder border as out param

- Source/Addins/MonoDevelop.GtkSharp.Addin/MonoDevelop.GtkSharp.Addin.csproj
building MonoDevelop.GtkSharp.Addin fails in CI
probably cause of updates in Mono & installed dotnet 5.0
works if:
adjust TargetFramework to net471  & adjust MonoDevelop.Addins to version 0.4.7
> MonoDevelop.GtkSharp.Addin.csproj: make CI happy

- Source/Libs/GdkSharp/GdkSharp.metadata
- Source/Samples/Sections/Miscellaneous/SeatSection.cs
This fixes issues with using the Gdk.Seat value returned by  `gdk_display_get_default_seat()`.
I mentioned this approach in the comments for https://github.com/GtkSharp/GtkSharp/pull/133#issuecomment-684115841, so that PR could be closed if this one is merged.
Fixes: #131
> Set the correct parent class for Gdk.SeatDefault

- Source/Libs/GLibSharp/Idle.cs
- Source/Libs/GLibSharp/InitiallyUnowned.cs
- Source/Libs/GLibSharp/Object.cs
- Source/Libs/GLibSharp/Source.cs
- Source/Libs/GLibSharp/Timeout.cs
- Source/Libs/GLibSharp/ToggleRef.cs
- Source/Libs/GLibSharp/Value.cs
- Source/Libs/GLibSharp/ValueArray.cs
- Source/Libs/GtkSharp/GtkSharp.metadata
- Source/Libs/GtkSharp/Widget.cs
- Source/Libs/GtkSourceSharp/Buffer.cs
- Source/Libs/Shared/Gapi.xsd
- Source/Tools/GapiCodegen/ClassBase.cs
- Source/Tools/GapiCodegen/Ctor.cs
- Source/Tools/GapiCodegen/StructField.cs
- Source/Tools/GapiCodegen/SymbolTable.cs
This backports a serie of patches from GlibSharp as we would like to base the GStreamer binding on top of this GtkSharp implementation and we have fixed quite a few things in there. Check commits independently for more details but the most import change is the proper fix of floating reference management (fixing https://github.com/GtkSharp/GtkSharp/issues/197).
> Cherry pick fixes from https://github.com/GlibSharp/GtkSharp/

- Source/Libs/GLibSharp/Idle.cs
- Source/Libs/GLibSharp/Object.cs
- Source/Libs/GLibSharp/Timeout.cs
- Source/Libs/GLibSharp/ToggleRef.cs
- Source/Libs/GtkSharp/Builder.cs
- Source/Libs/GtkSharp/MessageDialog.cs
- Source/Libs/GtkSharp/Widget.cs
This patch fixes some issues with disposing of widget and moving disposing of signals to the main thread.
Destroy should never be called, unless it is a TopLevel widget. Dispose will automatically call Destroy on TopLevel widgets.
It also introduce a new GetRawOwnedObject that should be used if it is not a toplevel widget, you are creating.
> Disposing of Widgets and Signals

- Source/Libs/GdkSharp/PixbufLoader.cs
Reverts GtkSharp/GtkSharp#203
Causes problems when loading pixbuf from stream so reverting it.
Fixes #216
> Revert "Don't add reference to PixbufHandle"

- Source/Libs/GioSharp/GioSharp.metadata
- Source/Libs/GtkSharp/GtkSharp.metadata
* [g_action_group_list_actions](https://developer.gnome.org/gio/stable/GActionGroup.html#g-action-group-list-actions)
Return type is owning NULL-terminated array
I suppose this fixes #165
* [gtk_entry_get_icon_area](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-get-icon-area)
Parameter `icon_area` is [out]
* [gtk_entry_get_text_area](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-get-text-area)
Parameter `text_area` is [out]
> Fixed some APIs according to GTK docs

- Source/Libs/GLibSharp/Signal.cs
After glib2 update to 2.68,  Signal.Flags marshaling is broken, ex value Flags.RunFirst is returned as RunFirst(100000000000000001b)
Fixes picoe/Eto#1914
Env: 
- ArchLinux
- glib2-2.68.0-5
- dotnet-runtime 5.0.4.sdk104-1
ps. not sure what they changed, it's possible that other structures are affected as well
> Correct flag check in Signal.Handler. Fixes issues for glib2 2.66 -> 2.68 update

- Source/Libs/GdkSharp/GdkSharp.metadata
- Source/Libs/GdkSharp/Pixbuf.cs
- Source/Libs/GdkSharp/PixbufAnimation.cs
Some `Pixbuf`, `PixbufAnimation` functions on Windows is exported with "_utf8" suffix.
I hid generated versions, copied and modified code to use "_utf8" on Windows.
Also hid `gdk_pixbuf_new_from_resource*`, `gdk_pixbuf_animation_new_from_resource` because they are using GResources and we already have constructors for .NET resources.
Fixes #230.
> Pixbuf Windows fixes (utf8 suffix)

- Source/Libs/GtkSharp/GtkSharp.metadata
- Source/Libs/GtkSharp/TreePath.cs
* `TreePath(int[])` constructor is now using one API call instead of many.
* `Indices` property is now using one API call instead of two.
> TreePath: Hide invalid API and use it for optimized manual functions

- Source/Libs/GtkSourceSharp/GtkSourceSharp.metadata
The match_start and match_end arguments in the searching functions of GtkSourceSearchContext are out parameters, as per the docs [here](https://developer.gnome.org/gtksourceview/stable/GtkSourceSearchContext.html#gtk-source-search-context-forward-finish).
> Fix some mistakes in GtkSourceSearchContext API

- Source/Libs/GLibSharp/Idle.cs
> GLib.Idle.Add: use expected default priority, add priority overload

- Source/Libs/GtkSharp/GtkSharp.metadata
IScrollableImplementor.GetBorder was not generated with out param as in IScrollable.
Supplements #201.
First line changed because of trimmed trailing space.
> Fix IScrollableImplementor.GetBorder out param

- Source/Libs/GLibSharp/Value.cs
Some GValue types support null value but code was not checking for .NET "null" and get null ref exception. Fixed nulls for g_value_set_variant, g_value_set_object, g_value_set_boxed as in GLib docs.
This fixes NodeView with null pixbuf column.
> Fixed GLib.Value nulls setter

- Source/Libs/CairoSharp/Path.cs
- Source/Libs/CairoSharp/PathData.cs
- Source/Libs/CairoSharp/PathDataType.cs
New properties on Path is lazy evaluated. Only reading is supported (you can't create path with custom pathdata).
Partially fixes #247.
> Added Cairo.Path properties

- Source/Samples/Samples.csproj
- Source/Templates/GtkSharp.Template.CSharp/content/GtkSharp.Application.CSharp/.template.config/template.json
- Source/Templates/GtkSharp.Template.CSharp/content/GtkSharp.Application.CSharp/GtkNamespace.csproj
- Source/Templates/GtkSharp.Template.FSharp/content/GtkSharp.Application.FSharp/.template.config/template.json
- Source/Templates/GtkSharp.Template.FSharp/content/GtkSharp.Application.FSharp/GtkNamespace.fsproj
- Source/Templates/GtkSharp.Template.VBNet/content/GtkSharp.Application.VBNet/.template.config/template.json
- Source/Templates/GtkSharp.Template.VBNet/content/GtkSharp.Application.VBNet/GtkNamespace.vbproj
- Source/Tools/GapiCodegen/GapiCodegen.csproj
- Source/Tools/GapiFixup/GapiFixup.csproj
- azure-pipelines.yml
I update not only samples, but also codegen tools, because .NET 5 is not LTS and in 4 month would be out.
Added template parameters, and resurrect netcoreapp3.1 support in templates.
Tested with following process
```
dotnet new --install Source/Templates/GtkSharp.Template.CSharp
...
dotnet new gtkapp -t net5.0
```
Closes #306
> Update to .NET 6

- Source/Libs/GdkSharp/GdkSharp.metadata
- Source/Libs/GdkSharp/Pixbuf.cs
This matches the other saving-related methods for Gdk.Pixbuf, and enables saving a pixbuf to a `GFile` stream
- `gdk_pixbuf_save_to_stream` was skipped for the auto-generated bindings (with the warning "Ellipsis parameter: hide and bind manually")
- `gdk_pixbuf_save_to_streamv` was in the generated bindings, but incorrect: the `option_keys` and `option_values` arguments had type `string` rather than `string[]`
> Implement Gdk.Pixbuf.SaveToStream() and SaveToStreamv()

- Source/GtkSharp.sln
- Source/Samples/Samples.csproj
- Source/Samples/Sections/Widgets/ListStoreSection.cs
Spinner was not spinning - should use `SetValue`, not `SetValues`.
Also fixed sln - VS2019 not want to open sln by double click in explorer - added empty line.
Also fixed sample project - VS2019 not showing all sources.
> Fixed sample for ListStore spinner

- Source/Libs/GLibSharp/Idle.cs
- Source/Libs/GLibSharp/Timeout.cs
`Idle.Add`, `Idle.AddSeconds`, `Timeout.Add`, `Timeout.AddSeconds` methods overloads are generalized:
* no priority (for default priority)
* enum priority (for standard priorities)
* int priority (for custom priority)
* overloads call main method with int priority
Fixed leak in `Timeout.Add(priority)`: method was not using `userData` and `DestroyHelper.NotifyHandler` as others.
> Generalized Idle and Timeout, fixed Timeout.Add

- Source/Libs/GLibSharp/GType.cs
AOT does not supports `Assembly.Load` and `Assembly.GetReferencedAssemblies()` when running AOT.
I opt-out of code which try to find type. In AOT context this means that you rely on dynamic type loading and you have issues anyway.
> Disable loading of additional assemblies in AOT context

- Source/Libs/GtkSharp/FileChooserNative.cs
Main changes are in `FileChooserNativeCreate`. GLib.Marshaller allows null strings args.
Also make consistent whitespaces, new lines.
> FileChooserNative: allow null parent, free memory

- Source/Libs/GLibSharp/Marshaller.cs
- Source/Libs/GtkSharp/TreeSelection.cs
- Source/Tools/GapiCodegen/ReturnValue.cs
Replace parts of marshaller responsible for lists/arrays with
AOT-friendly logic. Use generics where possible
> Reduce usage of Type

- Source/Tools/GapiCodegen/CallbackGen.cs
- Source/Tools/GapiCodegen/VirtualMethod.cs
Warnings produced complain that re-throw did not properly capture stack trace.
Given that these rethrow just to please compiler, I think it is better fix that.
> Fix bunch of warnings from code analysis

- Source/Libs/GLibSharp/DestroyNotify.cs
- Source/Libs/GLibSharp/Idle.cs
- Source/Libs/GLibSharp/Timeout.cs
- Source/Samples/Sections/Miscellaneous/TimerSection.cs
Fixed glib source double removal then using `Source.Remove` (`Timeout.Remove`, `Idle.Remove`).
I don't know if fix is correct or safe, but it solves problem that you can test in TimerDemo section from samples.
Repro:
If on Windows you should enable console in samples: `<OutputType>Exe</OutputType>`
Go to TimerDemo section and press buttons:
1. Add timer
2. Remove timer by handler
3. GC - no error in console
---
1. Add timer
2. Remove timer
3. GC - error in console "GLib-CRITICAL **: 20:29:41.579: Source ID 123 was not found when attempting to remove it"
> Fixed glib source double removal

- Source/Libs/GdkSharp/Pixbuf.cs
- Source/Libs/GdkSharp/PixbufAnimation.cs
- Source/Libs/GdkSharp/PixbufLoader.cs
- Source/Libs/GtkSharp/Builder.cs
- Source/Libs/GtkSharp/CssProvider.cs
- Source/Libs/GtkSharp/Image.cs
- Source/Libs/GtkSharp/UIManager.cs
Added no inlining attribute for methods with Assembly.GetCallingAssembly() so caller assembly is correct if jit want to inline.
See https://github.com/picoe/Eto/pull/2049.
> Fix loading of resources if jit inlines method

- Source/Libs/Shared/GLibrary.cs
brew used to install libraries under `/usr/local/` and GtkSharp still
expect this location.
https://github.com/GtkSharp/GtkSharp/blob/7995f132e19e18b8dae94359246540f059e53a86/Source/Libs/Shared/GLibrary.cs#L55
This fix will lookup the new library location `/opt/homebrew/lib/` if the
default ones (OS) or the `/usr/local/lib` could not load the libraries.
Reference: https://github.com/unoplatform/uno/issues/8296#issuecomment-1100435406
Fixes https://github.com/GtkSharp/GtkSharp/issues/249
> Fix loading native libraries on macOS (arm64) using homebrew installed gtk+3

- Source/Libs/GtkSharp/GtkSharp-api.xml
fix https://github.com/GtkSharp/GtkSharp/issues/299
https://docs.gtk.org/gtk3/signal.Widget.touch-event.html
defines: 
``
gboolean
touch_event (
GtkWidget* self,
GdkEvent* object,
gpointer user_data
)
``
definition in 
**GtkSharp-api.xml**
is **wrong**:
``
<signal name="TouchEvent" cname="touch-event" when="LAST" field_name="touch_event">
<return-type type="gboolean" />
<parameters>
<parameter type="GdkEventTouch*" name="event" />
</parameters>
</signal>
``
definition in
/usr/share/gir-1.0/Gtk-3.0.gir
``
<glib:signal name="touch-event" when="last">
<return-value transfer-ownership="none">
<type name="gboolean" c:type="gboolean"/>
</return-value>
<parameters>
<parameter name="object" transfer-ownership="none">
<type name="Gdk.Event"/>
</parameter>
</parameters>
</glib:signal>
`` …
> GtkSharp-api.xml: fix TouchEvent event-type

- Source/Libs/GdkSharp/GdkSharp.metadata
I need `gdk_event_handler_set` to create a global event handler as described here: https://stackoverflow.com/questions/64957969/can-i-set-up-a-global-gtk-accelerator-for-mouse-buttons?rq=1
See https://docs.gtk.org/gdk3/type_func.Event.handler_set.html
> Unhide EventHelper.HandlerSet method

- Source/Libs/GtkSharp/GtkSharp-api.xml
- Source/Libs/GtkSharp/GtkSharp.metadata
* SelectionBoxAlpha property is now generated.
* GtkRangeClass has correct ABI fields names.
* ColorHash is not generated but has correct type and already exists in manual code.
> Small not important API fixes

- Source/Libs/GioSharp/GioSharp.metadata
Fixes #359.
`data_size` renamed to detect it as count parameter for `data` array.
> Fixed g_content_type_guess array parameter

- Source/Libs/GLibSharp/KeyFile.cs
API is in GLib, not GObject library.
Also added Dispose, Set/Get Int64/UInt64.
> Fixed GLib.KeyFile

- Source/Libs/GtkSharp/NodeView.cs
Looks like copy-paste error from above GetBackgroundArea method
> Fixed NodeView.GetCellArea

- Source/Libs/GLibSharp/GType.cs
Old gtksharp2 name "pango-sharp" to new gtksharp3 name "PangoSharp".
Also added check to empty assembly location that will be in single file published projects.
> Fixed assembly search for requested type

- Source/Libs/GtkSharp/Bin.cs
- Source/Libs/GtkSharp/Box.cs
- Source/Libs/GtkSharp/Builder.cs
- Source/Libs/GtkSharp/ChildAttribute.cs
- Source/Libs/GtkSharp/Container.cs
- Source/Libs/GtkSharp/GtkSharp.metadata
- Source/Libs/GtkSharp/HandlerNotFoundException.cs
- Source/Libs/GtkSharp/SignalConnector.cs
- Source/Libs/GtkSharp/TemplateAttribute.cs
- Source/Libs/GtkSharp/Widget.cs
- Source/Samples/Sections/Widgets/CompositeWidgetSection.cs
- Source/Samples/Sections/Widgets/CustomWidgets/CompositeWidget.glade
Second version of template support.
Most code is from https://github.com/GtkSharp/GtkSharp/pull/90.
Auto signal connections are working, see samples.
Also added check for unknown fields (when GTK can't find widget in .glade).
But no .NET project templates, sorry.
> Add gtk composite template support v2
